% Sweave(file = ``./deletion-tdt.Rnw'')
\documentclass[10pt, final]{article}
\usepackage{Sweave}
\SweaveOpts{eps=FALSE,echo=TRUE,figs.only=TRUE,keep.source=FALSE, prefix.string=figures/deletion-tdt}
%\usepackage{fullpage}
%\usepackage{times}
%\usepackage[colorlinks=TRUE,urlcolor=blue,citecolor=blue]{hyperref}
%\usepackage{ifthen}  % Conditional 
%\usepackage{multicol}   %Columns
\usepackage{graphicx} %should be removed before submission!
\input{/home/sgy/jhsph/latex/sgy}
\begin{document}
<<options, echo=FALSE, eval = TRUE, echo = TRUE>>=
  options(width=75, continue = " ")
  library("Gviz")
  library("trioClasses")
  data("cnv", package = "trioClasses")
  data("pedigrees", package="CleftCNVAssoc")
  se <- SummarizedExperiment(assays = SimpleList(cnv = t(cnv.obj$cnv.mat)), colData = DataFrame(id=rownames(cnv.obj$cnv.mat), row.names = rownames(cnv.obj$cnv.mat)), rowData = cnv.obj$cmp.gr )
  beaty.trios <- MinimumDistance:::trios(beaty.pedigree)
  beaty.ped <- DataFrame(famid = do.call("rbind",strsplit(beaty.trios$O, "_" ))[,1], id = beaty.trios$O, fid = beaty.trios$F, mid = beaty.trios$M, sex = NA, dx = NA)
  ped <- PedClass(beaty.ped)
  fe <- FamilyExperiment(se, pedigree = ped )
@ 

<<FamilyExperiment, echo = TRUE, eval = TRUE>>=
  fe.parents <- fe[,colnames(fe)%in%parents(fe)]
@ 
<<freq-vec, echo = TRUE, eval = TRUE>>=
    freq.vec <- colSums(cnv(fe.parents))/nrow(cnv(fe.parents))
@ 
<<trioStates, eval = TRUE, echo = TRUE>>=
    trioAssay <- trioClasses:::TrioAssay(fe, type = "cnv")
    trioStates <- with(trioAssay, matrix( paste0(F,M,O), nrow = nrow(O), ncol = ncol(O)))
    dimnames(trioStates) <- dimnames(trioAssay$O)
@ 
<<table-list, eval = TRUE, echo = TRUE>>=
    table.list <- apply(trioStates, 2, "table")
@ 
<<transtab, eval = TRUE, echo = TRUE>>=
    trans.vec <- as( lapply( table.list, trioClasses:::trans.tab ), "numeric")
    head(table.list[which(trans.vec <= 0.05/length(trans.vec))])
@ 
\clearpage
\begin{center}
\begin{figure}
<<gviz, eval = TRUE, echo = TRUE, fig = TRUE, width = 8>>=

chr <- 8
gr.cnp <- cnv.obj$cmp.gr
gr.cnp.chr <- gr.cnp[as.logical(seqnames(gr.cnp) == paste0("chr", chr))]
    
p.vec <- trans.vec
p.vec.chr <- p.vec[as.logical(seqnames(gr.cnp) == paste0("chr", chr))]
freq.vec.chr <- freq.vec[as.logical(seqnames(gr.cnp) == paste0("chr", chr))]
    
library("TxDb.Hsapiens.UCSC.hg18.knownGene")
TranscriptDb <- TxDb.Hsapiens.UCSC.hg18.knownGene
atrack <- AnnotationTrack(reduce(gr.cnp.chr), name = "CNP comp.", fill = "darkgreen")
gtrack <- GenomeAxisTrack()
dtrack <- DataTrack( range = gr.cnp.chr, data = -log10(p.vec.chr), type = "p", cex = 1, name = "-log10(p)", ylim = c(0,10), col = "red" )
dtrack2 <- DataTrack( range = gr.cnp.chr, data = ifelse(freq.vec.chr > 0.01, freq.vec.chr, NA ), type = "s", col = "blue", cex = 1, name = "Frequency", ylim = c(0,1), lwd = 2 )
itrack <- IdeogramTrack(genome = "hg18", chromosome = paste0("chr", chr), lty = 1, lwd = 1 )
grtrack <- GeneRegionTrack(TranscriptDb, genome="hg18", chromosome=chr, name="UCSC Known Transcripts", showId = TRUE)

fud <- 5e5/2
plotTracks(list(dtrack, dtrack2, grtrack, gtrack, itrack ),  background.panel = '#FFFEDB', background.title = 'darkblue', from = 39356825 - fud, to = 39497557 + fud)

@ 
\label{chr8-locus}
\caption{Foo!}
\end{figure}
\end{center}
\includegraphics{./figures/ucsc}
%%     <<n-tests, eval = TRUE, echo = TRUE>>=
%%     n.tests <- sum(!is.na(trans.vec))
%% @ 
%%     <<reduce-locus, eval = TRUE, echo = TRUE >>=
%%     locus <- reduce(cnv.obj$cmp.gr[which(trans.vec <= 0.05/n.tests)])
%%     wd <- width(locus)/1e3
%% @ 
%%     <<trans.tab, eval = TRUE, echo = TRUE >>=
%%     trioClasses:::trans.tab
%% @ 

\end{document}
