% Sweave(file = "./ScanTrio.Rnw")
\documentclass[10pt]{article}
<<echo=FALSE>>=
  options(width=70, continue = " ")
@
\SweaveOpts{eps=FALSE,echo=TRUE,figs.only=TRUE,keep.source=FALSE, prefix.string=figures/ScanTrio}
\usepackage{fullpage}
\usepackage{times}
\usepackage[colorlinks=TRUE,urlcolor=blue,citecolor=blue]{hyperref}
\title{The R package \emph{trioClasses} for definition of the class \emph{FamilyExperiment}, an extension of \emph{SummarizedExperiment}, for use in trio based analyses of genetic data.}
\author{Samuel G. Younkin}%, Robert Scharpf, Holger Schwender, Ingo Ruczinski}
\date{\today}
%\input{/home/bst/student/syounkin/jhsph/latex/sgy}
%\input{/home/sgy/jhsph/latex/sgy}
\begin{document}
\setlength{\parskip}{0.2\baselineskip}
\setlength{\parindent}{0pt}
\maketitle
\section{Packages \& Data}
<<package>>=
library("trioClasses")
data("cleft.ts.pedigree")
data("8q24-european-all.sm")
@
<<prelim, echo = FALSE, eval = TRUE>>=
pos <- as(do.call("rbind", strsplit(colnames(sm),split = ":") )[,2], "integer" )
chr <- do.call("rbind", strsplit(colnames(sm),split = ":") )[,1]
gr <- GRanges( seqnames = chr, ranges = IRanges(start = pos, width = 1), strand = "*" )
names(gr) <- colnames(sm)
col.DF <- DataFrame( id = rownames(sm) )
rownames(col.DF) <- rownames(sm)
@ 
\section{SummarizedExperiment}
<<data, echo = TRUE>>=
se <- SummarizedExperiment(assays = SimpleList(geno = t(sm)), colData = col.DF, rowData = gr )
@ 
\section{Pedigree}
<<ped>>=
ped <- PedClass(cleft.ts.pedigree)
@ 
\section{FamilyExperiment}
<<fe>>=
(fe <- FamilyExperiment(se, pedigree = ped ))
@ 
\section{ScanTrio}
The two implementations (R, C++) do not share a common method to deal with missing genotypes.  So we remove all missingness for comparison.
<<missingness>>=
na.markers <- which(colSums(is.na(geno(fe)))>0) # Identify markers that have at least one NA call
(fe <- fe[-na.markers])                        # Removing these markers removes all missing data
@ 
<<scantrio>>=
wd <- 50e3
window <- GRanges( seqnames = seqnames(fe), ranges = IRanges(start = start(rowData(fe)), width = wd ) )
(scan.trio <- ScanTrio( object = fe[MAF(fe)<=0.01], window = window, block = range(rowData(fe))))
@ 
The following function creates the files needed to run scan-trio-cpp.  The following command writes four files to the current working directory --- 8q24.ped, 8q24.map, 8q24.blocks, 8q24.weights.  Use these with scan-trios to compare.  Please note which versions of trioClasses and scan-trios you are using.
<<make-files-for-cpp>>=
trioClasses:::make.files.for.cpp(fe, fileroot = "./8q24")
@ 
\end{document}
