:toc:
:numbered:
:data-uri:

<<junk,echo=FALSE>>=    Somehow, this avoids the "figure margins too large" error ~kbroman
par(mar=rep(0,4))
@

<<options, echo=FALSE, eval = TRUE, echo = FALSE>>=
  options(width=75, continue = " ")
  library("Trioconductor")
@ 

== Toy Pedigree ==
We start with a toy pedigree and map file, and read them in using ped2fe.  The ped2fe function is built on snpStats:::read.pedfile.

<<toyped>>=
(fe <- Trioconductor:::ped2fe(ped = "./../inst/small.ped", map = "./../inst/small.map"))
@
Now we may coerce the FE object to a genotype matrix suited for the trio package.
<<coerce>>=
(geno.trio <- as(fe,"matrix"))
@

Here is the ped file, "small.ped":
----
DS10776 H_ME-DS10776_2-DS10776_2 0 0 1 1 1 2 2 2 0 0
DS10776 H_ME-DS10776_3-DS10776_3 0 0 2 1 2 2 2 2 2 2
DS10776 H_ME-DS10776_1-DS10776_1 H_ME-DS10776_2-DS10776_2 H_ME-DS10776_3-DS10776_3 2 2 1 2 2 2 2 2
DS10777 H_ME-DS10777_2-DS10777_2 0 0 1 1 1 2 2 2 2 2
DS10777 H_ME-DS10777_3-DS10777_3 0 0 2 1 1 2 2 2 2 2
DS10777 H_ME-DS10777_1-DS10777_1 H_ME-DS10777_2-DS10777_2 H_ME-DS10777_3-DS10777_3 2 2 1 2 2 2 2 2
----

And here is the map file, "small.map":
----
8	chr8:129296000	0	129296000
8	chr8:129296113	0	129296113
8	chr8:129296185	0	129296185
----

== FE Methods  ==
Now we explore some of the methods associate with FE.
<<rowdata>>=
rowData(fe)
@

<<coldata>>=
colData(fe)
@

<<MAF>>=
MAF(fe)
@
We may use Trioconductor to create a list of three matrices, F, M and O.  A simple concatenation of these matrices gives a matrix of trio-states at each SNP-trio pair.
<<TrioAssay>>=
Trioconductor:::TrioAssay(fe, type = "geno")
@
We may also use Trioconductor to count transmissions and Mendelian errors in a given region defined by a GRanges object.

<<TransCount>>=
Trioconductor:::TransCount(fe, rowData(fe) )
@

Above we see there were four observeable transmission of which 1 minor allele was transmitted and 2 major alleles were transmitted.  There are no Mendelian errors. Foo!