% Sweave(file = "./trioClasses.Rnw")
\documentclass[10pt]{article}
<<echo=FALSE>>=
  options(width=70, continue = " ")
@
\SweaveOpts{eps=FALSE,echo=TRUE,figs.only=TRUE,keep.source=FALSE, prefix.string=figures/trioClasses}
\usepackage{fullpage}
\usepackage{times}
\usepackage[colorlinks=TRUE,urlcolor=blue,citecolor=blue]{hyperref}
\title{The R package \emph{trioClasses} for definition of the class \emph{SNPTrioExperiment}, an extension of \emph{SummarizedExperiment}, for use in trio based analyses of genetic data.}
\author{Samuel G. Younkin, Robert Scharpf, Holger Schwender, Ingo Ruczinski}
\date{\today}
%\input{/home/bst/student/syounkin/jhsph/latex/sgy}
%\input{/home/sgy/jhsph/latex/sgy}
\begin{document}
\setlength{\parskip}{0.2\baselineskip}
\setlength{\parindent}{0pt}
\maketitle
\section{Sample Data}
<<data, echo = TRUE>>=
data("sample")
@ 
\section{Classes}
<<packages, echo = FALSE>>=
library("trioClasses")
#library("snpStats")
#library("vcf2R")
@
\subsection{SnpMatrix, DataFrame, GRanges} 
The four key ingredients are the SNP matrix, the pedigree information as a DataFrame, position of the SNPs given by a GRanges object, and covariate data given as a DataFrame.
<<grdf2>>=
sm
ped.DF
gr
@ 
\subsection{SummarizedExperiment}
We combine three of the key ingredients when we create the SummarizedExperiment object.
<<se>>=
se <- SummarizedExperiment(assays = SimpleList(geno = t(sm)), colData = col.DF, rowData = gr )
@ 
\subsection{SNPTrioExperiment}
Now, we include the pedigree information as an object of class PedClass.  We keep PedClass independent of SNPTrioExperiment for flexibility.
<<ste>>=
ped <- PedClass(ped.DF)
ste <- SNPTrioExperiment(se, pedigree = ped )
@ 
Here is the show method.
<<ste-show>>=
ste
@ 
And now we verify that it is indeed an extension of SummarizedExperiment.
<<ste-class>>=
getClass("SNPTrioExperiment")
@ 
\subsection{PedClass}
Now we investigate the pedigree slot of the SNPTrioExperiment object.
<<classes>>=
class(pedigree(ste))
getClass("PedClass")
pedigree(ste)
@
\subsection{geno accessor}
<<geno>>=
class(geno(ste))
getClass("SnpMatrix")
geno(ste)
@ 
\subsection{RowData}
<<rowdata>>=
rowData(ste)
@ 
\subsection{ColData}
<<coldata>>=
colData(ste)
@ 
Now create a list of three SnpMatrices for trio analyses.
<<genotrio>>=
gtrio <- GenoTrio(ste)
#O.geno <- as(gtrio$O, "numeric" )
#F.geno <- as(gtrio$F, "numeric" )
#M.geno <- as(gtrio$M, "numeric" )
trans.011 <- sum(gtrio$F == 0 & gtrio$M == 1 & gtrio$O == 1, na.rm = TRUE)
#trans.011 <- sum(F.geno == 0 & M.geno == 1 & O.geno == 1, na.rm = TRUE)
@ 
\section{Validity}
\section{Methods}
\end{document}
