setGeneric("geno", function(object) standardGeneric("geno"))
setGeneric("logR", function(object) standardGeneric("logR"))
setGeneric("baf", function(object) standardGeneric("baf"))
setGeneric("pedigree", function(object) standardGeneric("pedigree"))
setGeneric("completeTrios", function(object) standardGeneric("completeTrios"))
setGeneric("ids", function(object) standardGeneric("ids"))
setGeneric("SNPTrioExperiment", function(se, pedigree) standardGeneric("SNPTrioExperiment"))
setGeneric("CNVTrioExperiment", function(se, pedigree) standardGeneric("CNVTrioExperiment"))
setGeneric("PedClass", function(object) standardGeneric("PedClass"))
setGeneric("trios", function(object) standardGeneric("trios"))
setGeneric("GenoTrio", function(object) standardGeneric("GenoTrio"))
setGeneric("ctcbind", function(object) standardGeneric("ctcbind"))
setGeneric("TransCount", function(object, region) standardGeneric("TransCount"))
setGeneric("ScanTrio", function(object, window, block) standardGeneric("ScanTrio"))
setGeneric("parents", function(object) standardGeneric("parents"))
setGeneric("MAF", function(object) standardGeneric("MAF"))
setGeneric("aTDT", function(object) standardGeneric("aTDT"))
setGeneric("relist.sgy", function(object) standardGeneric("relist.sgy"))
#setGeneric("setdiff.sgy", function(subject, query) standardGeneric("setdiff.sgy"))
