setGeneric("geno", function(object) standardGeneric("geno"))
setGeneric("logR", function(object) standardGeneric("logR"))
setGeneric("baf", function(object) standardGeneric("baf"))
setGeneric("show", function(object) standardGeneric("show"))
setGeneric("Pedigree", function(object) standardGeneric("Pedigree"))
setGeneric("completeTrios", function(object) standardGeneric("completeTrios"))
