setGeneric("trios", function(object) standardGeneric("trios"))
setGeneric("trioIndex", function(object) standardGeneric("trioIndex"))

setGeneric("offspringNames", function(object) standardGeneric("offspringNames"))
setGeneric("fatherNames", function(object) standardGeneric("fatherNames"))
setGeneric("motherNames", function(object) standardGeneric("motherNames"))
setGeneric("sampleNames", function(object) standardGeneric("sampleNames"))
setGeneric("allNames", function(object) standardGeneric("allNames"))
setGeneric("geno", function(object) standardGeneric("geno"))
setGeneric("getGeno", function(object, ...) standardGeneric("getGeno"))
setGeneric("getMAF", function(object) standardGeneric("getMAF"))

setGeneric("completeTrios", function(object, id.vec) standardGeneric("completeTrios"))
setGeneric("pedigree", function(object) standardGeneric("pedigree"))
setGeneric("trios", function(object) standardGeneric("trios"))
